- name: "Criando vms"
  vmware_guest:
    hostname: "{{ ansible_vmware_host }}"
    username: "{{ ansible_vmware_user }}"
    password: "{{ ansible_vmware_password }}"
    validate_certs: False
    name: "{{ inventory_hostname }}"
    template: ubuntu-1804-template
    datacenter: "{{ datacenter_name }}"
    folder: /{{ datacenter_name }}/vm
    #esxi_hostname: "{{ host_name }}"
    cluster: "{{ cluster_name }}"
    datastore: "{{ vsphere_datastore }}"
    #disk: 
    #- size_gb: 32
    #  type: thin
    hardware:
      memory_mb: 8144
      num_cpus: 4
      num_cpu_cores_per_socket: 2
      hotadd_cpu: True
      hotadd_memory: True
    networks:
    - name: vlan
      ip: "{{ vlan_ip }}"
      netmask: 255.255.255.0
      gateway: 10.10.10.1
      type: static
      dns_servers: 
        - 10.10.10.1
      dns_suffix:
        - domain
    customization:
      domain: domain
      dns_servers:
        - 10.10.10.1
    state: poweredon
    wait_for_ip_address: yes
  delegate_to: localhost

- name: "Trocando o hostname"
  vmware_vm_shell:
    hostname: "{{ ansible_vmware_host }}"
    username: "{{ ansible_vmware_user }}"
    password: "{{ ansible_vmware_password }}"
    validate_certs: False
    datacenter: "{{ datacenter_name }}"
    folder: "/{{datacenter_name}}/vm"
    vm_id: "{{ inventory_hostname }}"
    vm_username: "{{ ansible_vmware_tools_user }}"
    vm_password: "{{ ansible_vmware_tools_password }}"
    vm_shell: "/usr/bin/hostnamectl"
    vm_shell_args: "set-hostname {{ inventory_hostname }} > /tmp/$$.txt 2>&1"
    wait_for_process: True
  delegate_to: localhost